# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
# don't use xcpretty until compatibility with codecov is restored
#- set -o pipefail && xcodebuild test -workspace Example/MDNotificationView.xcworkspace -scheme MDNotificationView-Example -sdk iphonesimulator10.2 ONLY_ACTIVE_ARCH=NO -destination 'OS=10.0,name=iPhone SE' | xcpretty
- set -o pipefail && xcodebuild test -workspace Example/MDNotificationView.xcworkspace -scheme MDNotificationView-Example -sdk iphonesimulator10.2 ONLY_ACTIVE_ARCH=NO -destination 'OS=10.0,name=iPhone SE' -enableCodeCoverage YES
- pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
