# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c

# cache: cocoapods
# podfile: Example/Podfile

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

script:
- xcodebuild -workspace Example/MDNotificationViewExample.xcworkspace -list
- set -o pipefail && xcodebuild clean build test -project MDNotificationView.xcodeproj -scheme MDNotificationView -sdk iphonesimulator10.2 ONLY_ACTIVE_ARCH=YES -destination 'OS=10.0,name=iPhone SE' | xcpretty
- set -o pipefail && xcodebuild clean build -workspace Example/MDNotificationViewExample.xcworkspace -scheme MDNotificationViewExample | xcpretty

- pod lib lint

after_success:
- bash <(curl -s https://codecov.io/bash) -J "MDNotificationView"

